# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Author:
    id: int
    name: str
    bio: Optional[str]


@dataclasses.dataclass()
class Book:
    id: int
    title: str
    author_id: int
    isbn: str
    published: datetime.date
